# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coperative',
        ),
        migrations.RemoveField(
            model_name='sessionlevels',
            name='account',
        ),
        migrations.RemoveField(
            model_name='voicecall',
            name='account',
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='loan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='SessionLevels',
        ),
        migrations.DeleteModel(
            name='VoiceCall',
        ),
    ]
