# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd_app', '0002_auto_20180615_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='account_number',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='bank_code',
            field=models.IntegerField(max_length=25, null=True),
        ),
    ]
