# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd_app', '0003_auto_20180615_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bank_code',
            field=models.IntegerField(null=True),
        ),
    ]
