# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ussd_app', '0005_auto_20180615_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='ussd_app.Account'),
        ),
    ]
