# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd_app', '0006_auto_20180615_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('concluded', 'Concluded'), ('declined', 'Payed')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trans_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
